version: "3.9"
services:
  web:
    build: .
    hostname: web
    environment:
      - REDIS_HOST=redis
    networks:
      - redis-net
      - proxy-net
    depends_on:
      - redis
    restart: unless-stopped

  caddy-proxy:
    image: caddy:alpine
    restart: unless-stopped
    networks:
      - proxy-net
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      # - $PWD/site:/srv
      - caddy-data:/data
      - caddy-config:/config

  redis:
    image: "redis:alpine"
    hostname: redis
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - redis-net
    volumes:
      - redis-data:/data
    restart: unless-stopped

  redis_insight:
    image: redislabs/redisinsight:latest
    networks:
      - redis-net
    ports:
      - 8001:8001
    volumes:
      - redis-insight-data:/db
    restart: unless-stopped

networks:
  redis-net:
  proxy-net:

volumes:
  redis-data:
  caddy-data:
  caddy-config:
  redis-insight-data:
