version: "3.9"
services:
  web:
    build: .
    environment:
      - REDIS_HOST=redis
    ports:
      - "3000:3000"
    networks:
      - redis-net
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: "redis:alpine"
    hostname: redis
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - redis-net
    volumes:
      - redis-data:/data
    restart: unless-stopped

  redis_insight:
    image: redislabs/redisinsight:latest
    networks:
      - redis-net
    ports:
      - 8001:8001
    volumes:
      - redis-insight-data:/db
    restart: unless-stopped

networks:
  redis-net:

volumes:
  redis-data:
  redis-insight-data:
