version: "3.9"
services:
  nodejs:
    build: .
    environment:
      - REDIS_HOST=redis
      - VIRTUAL_HOST=472.se
      - VIRTUAL_PORT=3000
    expose:
      - "3000"
    networks:
      - redis-net
    depends_on:
      - redis
    restart: unless-stopped

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock

  redis:
    image: "redis:alpine"
    hostname: redis
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - redis-net
    volumes:
      - redis-data:/data
    restart: unless-stopped

  redis_insight:
    image: redislabs/redisinsight:latest
    networks:
      - redis-net
    ports:
      - 8001:8001
    volumes:
      - redis-insight-data:/db
    restart: unless-stopped

networks:
  redis-net:

volumes:
  redis-data:
  redis-insight-data:
